import Head from 'next/head'
import { PostCard,Categories,PostWidget } from '../components/index'

export default function Home() {

  const posts = [
    { title: 'React Testing', except: 'Learn React with Tailwind' },
    { title: 'React with Tailwind', except: 'learn React with Tailwind' },
  ]

  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Cms Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {
            posts.map((post, index) => {

              return (
                <PostCard post={post} key={post.title} />
              )
              
              

              
  
            })
          }
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget/>
            <Categories/>
          </div>

        </div>
      </div>

    </div>
  )
}
